# Randomized crop management response trials {#mrt}

*Edited by: Jordan Chamberlin, Markus Walsh, ...?*

## Introduction {#mrt-intro}

Inherently low soil fertility, nutrient imbalances and potentially accelerating soil physical, chemical and biological degradation, are thought to constitute threats to maintaining agricultural productivity and other ecosystem services across Africa's cropland biome. However, at present the geographical extent of existing soil problems in croplands, their location specific trends and opportunities for managing these over time are not known. Some of the key information gaps include:

* The cropland area and the proportion of arable land that is being used for cultivation has not been adequately identified with sufficient accuracy to allow spatial targeting of appropriate management practices. 
* Rapidly growing populations in Africa (currently estimated at ~ ?? M, and projected to ~?? M by 2030) will require substantial increases in either agricultural productivity per unit of currently cultivated land area and/or the expansion of cultivated lands to meet food demands.
* The rate of yield increases in staple cereal crops (e.g., maize, sorghum, rice and other field crops) may be slowing and various soil constraints appear to be one important factor influencing this trend. However, the spatial distribution of these constraints is not known and it is therefore difficult to devise location specific nutrient input and crop management recommendations. 
* Economically viable and ecologically sustainable nutrient input/import options have not been previously established at sub-national scales or for specific agro-ecologies and landuse systems. As a consequence, blanket fertilizer formulations and other agro-input recommendations are being blindly applied countrywide.
* Soil degradation reduces agricultural productivity and other ecosystem service deliveries to people. However, the geographical distribution, rates and impacts of important soil degradation processes (e.g. wind and water erosion, organic matter and nutrient depletion, acidification, salinization, alkalization, compaction, loss of below ground biodiversity) are poorly documented and understood. 
* Water-use efficiency in crop and rangeland production systems is determined in part by soil management. Again, the actual and potential water use efficiencies of agricultural systems in Africa (and elsewhere) are poorly characterized and should be assessed to evaluate e.g. the potential tradeoff’s between needs for agricultural production and the availability of potable water for rapidly growing human populations.
* Changing climatic conditions may increasingly disrupt current land use systems. The sustainability of these systems will depend on interactions between climate, soil, and land management as well as by the policies that enable or undermine them. 

An ability to track these potential changes and anticipate the attendant consequences requires reliable information about the characteristics and distribution of cropland productivity and the potentials for improvement, given interventions. One of the most reliable and informative ways of monitoring both the current situation and the potentials is by using [**Randomized Controlled Trials**](https://en.wikipedia.org/wiki/Randomized_controlled_trial) (RCT). However, the main problems with all RCTs is that they are usually logistically difficult and quite expensive to conduct.


## Nigeria data {#NG-data}

```{r}
# install.packages(c("downloader","rgdal","raster","arm","leaflet","htmlwidgets")), dependencies=TRUE)
suppressPackageStartupMessages({
  require(downloader)
  require(rgdal)
  require(sp)
  require(raster)
  require(arm)
  require(leaflet)
  require(htmlwidgets)
})

# Create a data folder in your current working directory
dir.create("OCP_data", showWarnings=F)
setwd("./OCP_data")

# Data downloads -----------------------------------------------------------
# download IITA/OCP yield data
download("https://www.dropbox.com/s/hi75cnp3ejr4srk/OCP_trials.zip?raw=1", "OCP_trials.zip", mode = "wb")
unzip("OCP_trials.zip", overwrite = T)
sites <- read.table("sites.csv", header=T, sep=",")
trial <- read.table("trials.csv", header=T, sep=",")
tresp <- merge(sites, trial, by="sid")

# download GADM-L2 shapefile (courtesy: http://www.gadm.org)
download("https://www.dropbox.com/s/y3h6l7yu00orm78/NGA_adm2.zip?raw=1", "NGA_adm2.zip", mode = "wb")
unzip("NGA_adm2.zip", overwrite = T)
shape <- shapefile("NGA_adm2.shp")

# download raster stack (note this is a big 800+ Mb download)
download("https://www.dropbox.com/s/u5fyjbujf0d7q43/NG_250m_2017.zip?raw=1", "NG_250m_2017.zip", mode = "wb")
unzip("NG_250m_2017.zip", overwrite = T)
glist <- list.files(pattern="tif", full.names = T)
grids <- stack(glist)

# Data setup --------------------------------------------------------------
# attach GADM-L2 admin unit names from shape
coordinates(tresp) <- ~lon+lat
projection(tresp) <- projection(shape)
gadm <- tresp %over% shape
tresp <- as.data.frame(tresp)
tresp <- cbind(gadm[ ,c(5,7)], tresp)
colnames(tresp) <- c("state","lga","sid","lat","lon","alt","team","trt","ccob","tcob","twgt","cyld","tyld","ayld")

# project survey coords to grid CRS
tresp.proj <- as.data.frame(project(cbind(tresp$lon, tresp$lat), "+proj=laea +ellps=WGS84 +lon_0=20 +lat_0=5 +units=m +no_defs"))
colnames(tresp.proj) <- c("x","y")
tresp <- cbind(tresp, tresp.proj)
coordinates(tresp) <- ~x+y
projection(tresp) <- projection(tresp)

# extract gridded variables at survey locations
trespgrid <- extract(grids, tresp)
gsdat <- as.data.frame(cbind(tresp, trespgrid)) 
# plot(alt~MDEM, gsdat) ## gps altitude/location check against MDEM 

# Classify by site indices ------------------------------------------------
si.lmer <- lmer(log(tyld)~trt*+(1|sid), gsdat) ## random intercept (site-level) model
display(si.lmer)
si.ran <- ranef(si.lmer) ## extract random effects
si <- as.data.frame(rownames(si.ran$sid))
si$si <- si.ran$sid[,1]
colnames(si) <- c("sid","si")
si$sic <- ifelse(si$si > 0, "A", "B") ## classify above/below average site indices (sic = A/B)
gsdat <- merge(gsdat, si, by="sid")
si <- merge(si, sites, by="sid")

# Plots
boxplot(tyld~trt, notch=T, ylab="Cob yield (kg/ha)", ylim=c(0,8000), gsdat) ## treatment differences
boxplot(tyld~sic, notch=T, ylab="Cob yield (kg/ha)", ylim=c(0,8000), gsdat) ## yield differences between site index classes
boxplot(tcob~trt*sic, notch=T, ylab="Number of cobs", ylim=c(0,800), gsdat) ## treatment differences
boxplot(tyld~trt*sic, notch=T, ylab="Cob yield (kg/ha)", ylim=c(0,8000), gsdat) ## treatment differences
plot(tyld~cyld, xlab="Cob yield (kg/ha), circular plot", ylab="Cob yield (kg/ha), total plot", gsdat)

# extract gridded variables at trial locations
si.proj <- as.data.frame(project(cbind(si$lon, si$lat), "+proj=laea +ellps=WGS84 +lon_0=20 +lat_0=5 +units=m +no_defs"))
colnames(si.proj) <- c("x","y")
si <- cbind(si, si.proj)
coordinates(si) <- ~x+y
projection(si) <- projection(tresp)
sigrid <- extract(grids, si)
sidat <- as.data.frame(cbind(si, sigrid)) 

# Write data frames -------------------------------------------------------
dir.create("Results", showWarnings = F)
write.csv(gsdat, "./Results/OCP_gsdat.csv", row.names = F)
write.csv(sidat, "./Results/OCP_sidat.csv", row.names = F)

# Yield trial map widget --------------------------------------------------
w <- leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap.Mapnik) %>%
  addCircleMarkers(si$lon, si$lat, clusterOptions = markerClusterOptions())
w ## plot widget 
saveWidget(w, 'OCP_trials.html', selfcontained = T) ## save widget
```
